### ISSUE TITLE
Chapter Flow and Readability of TLU Reports

### ISSUE THREAD

**Issue by anselld** [tari-labs/tari-university#133]
Activity 3 of SoW for TLU Content Technical Editing.

**Comment by anselld** [comment]
# Chapter Flow and Readability of TLU Reports



## Introduction

This document comments on the chapter flow and readability of TLU's online articles. It suggests a more logical structure for chapters/content.



## Chapter Flow and Readability

A consistent document structure and edited content can improve readability and make documents user-friendly. There is little consistency in the structure and language used in the TLU chapters. This could be greatly improved by editing and formatting all TLU chapters in accordance with the requirements of the TLU Style Guide.

Some overall suggestions to improve chapter flow and readability:

- Format each section in each chapter consistently.

- Structure the information well to orientate the reader and communicate the information across clearly.

- Present important information first.

- Use clear, easily understandable words.

- Use active verbs to clarify the meaning of a sentence.

  

## Observations and Suggestions

### General

Chapters and sections in the TLU content are not structured consistently. With reference to the index of the TLU online content:

#### Chapter Front Pages

The first page of Chapters 1 to 6 provides useful definitions (from online sources) of the chapter headings. A brief opening paragraph preceding the definitions in each of these chapters would set the scene and introduce the reader to the subject matter. Chapter 7 provides an example of an introduction.

For consistency in layout of the front pages, here are suggested front page headings for Chapter 1, Cryptography. These headings could be applied to the front pages of all the chapters:

**Cryptography**

**Purpose**

The purpose of cryptography is to protect data transmitted in the likely presence of an adversary [1]. 

**Definitions**

- From [**Wikipedia**](https://en.wikipedia.org/wiki/Cryptography)

  Cryptography or cryptology (from Ancient Greek: κρυπτός, kryptós "hidden, secret"; and γράφειν graphein, "to write", or -λογία -logia, "study", respectively) is the practice and study of techniques for secure communication in the presence of third parties called adversaries. More generally, cryptography is about constructing and analyzing protocols that prevent third parties or the public from reading private messages; various aspects in information security such as data confidentiality, data integrity, authentication, and non-repudiation are central to modern cryptography.

- From [**SearchSecurity**](https://searchsecurity.techtarget.com/definition/cryptography)

  Cryptography is a method of protecting information and communications through the use of codes so that only those for whom the information is intended can read and process it. The pre-fix "crypt" means "hidden" or "vault" and the suffix "graphy" stands for "writing."

**References**

[1]

[2]

[3]

(Insert only the references (e.g. containing the definitions) that appear on this first page of the chapter.)



### Specifics

With reference to the index of the TLU online content:

#### Introduction

The introduction in the TLU online content appears repetitive and confusing. "Presentations" and "Reports" do not seem to belong under the "Learning Paths" section. The "Presentations" information could be more useful to the reader if placed under the relevant chapter or section heading, to explain what the presentation is about. The "Reports" information is repeated in the pane on the left, and could be removed from the introduction.

The introduction would then be left with the "Beginners", "Step-up from Beginners" and "Lay of the Land" sections. It is unclear how the third section relates to the "Learning Paths" section.

Perhaps under "Learning Paths" there could be some introductory text, followed by three sections: Beginners, Intermediate and Advanced. The current chapter and section topics could then be placed under these headings (either listed or tabulated).

#### Chapter 1 - Cryptography 

- Section 1.1 - Elliptic Curves 101. This section contains a presentation, with no explanatory text for the reader. To introduce a consistent style for presentations, the introductory text in "Introduction", under "Beginners" could be inserted before the presentation. (As suggested in the preceding section.)

  *Example*

  "This presentation is an introduction to elliptic curve math and digital signatures."  

- Section 1.2 - Introduction to Schnorr Signatures - currently formatted and being edited as per the TLU Style Guide. 

  Section 1.3 - Introduction to Scriptless Scripts - is as per the TLU Style Guide.

- Section 1.4 - The MuSig Schnorr Signature Scheme - should be edited and formatted.

- Section 1.5 - Fraud Proofs - is as per the TLU Style Guide.

- Section 1.6 - Bulletproofs and Mimblewimble - should be edited and formatted.

- Section 1.7 - The Bulletproof Protocols - should be edited and formatted.

- Section 1.8 - Pure-Rust Elliptic Curve Cryptography - contains a video (presentation) on pure rust cryptography, with no explanatory text for the reader. For consistency in section layout, a brief introduction could be inserted before the presentation, to orientate the reader.

#### Chapter 2 - Consensus Mechanisms

- It is unclear why sections 2.2.2 and 2.2.3 are called Part 1 and Part 2 respectively. Perhaps explain why this was done; or perhaps the sections could be combined.
- Suggest combining sections 2.2.4, 2.2.5 and 2.2.6.

#### Chapter 3 - Layer 2 Scaling

- Move the presentation (section 3.3 - Executive Summary) to before section 3.1, and insert (above the presentation) the introductory text from the TLU Introduction section.
- It is unclear why sections 3.1 and 3.2 are called Part 1 and Part 2 respectively. Perhaps explain why this was done; or perhaps the sections could be combined.

#### Chapter 4 - Merged Mining

This chapter is structured as per the TLU Style Guide.

#### Chapter 5 - Digital Assets

- Insert a second-level heading under Digital Assets, namely Terminology. Then under that heading, insert two level-three headings: Digital Assets and Non-fungible Tokens.
- In section 5.1, in line with preceding suggestions regarding presentations, lead into the presentation (under Non-fungible Tokens) with the following text from the TLU Introduction section: "This presentation provides an introduction to non-fungible tokens (NFTs), including the implementation of NFTs, Ethereum standards, and players in the Blockchain-based ticketing industry."
- Edit and format section 5.2 in accordance with the TLU Style Guide.

#### Chapter 6 - Protocols

- Introduce the reader to the presentation in section 6.1 with the following text from the TLU Introduction section: "This presentation introduces Mimblewimble - a protocol that focuses on scalability and privacy through the implementation of confidential transactions."
- Edit and format sections 6.2 to 6.5 in accordance with the TLU Style Guide.
- Introduce the reader to the presentations in sections 6.6, 6.7 and 6.8 by preceding the presentations with the relevant introductory text from the TLU Introduction section.

#### Chapter 7 - Labs

- Edit and format the chapter in accordance with the TLU Style Guide.
- Insert a list of references and list of contributors.



## Conclusion

Contributors' writing styles may differ - this is understandable and welcome. However, for effective communication, contributors' language within a chapter or section needs to be well structured, linguistically correct, consistent and clear. Good writing, editing and presentation can help ensure the quality of TLU's documentation in support of its mission: To be the premier destination for balanced and accessible learning material for blockchain, digital currency and digital assets learning material.

**Comment by anselld** [comment]
@hansieodendaal 
Hansie, here is Activity 3. Your comments are welcome.

**Comment by CjS77** [comment]
This is very helpful, thank you @anselld.  I think the next step is to break some of these recommendations out into separate issues.

**Comment by hansieodendaal** [comment]
All these issues were addressed in multiple PRs.
