### ISSUE TITLE
Re-license to CC BY-NC-SA 4.0 or CC BY-SA 4.0

### ISSUE THREAD

**Issue by CjS77** [tari-labs/tari-university#137]
Relicense TLU content to CC with Attribution

**Comment by hansieodendaal** [comment]
https://creativecommons.org/publicdomain/zero/1.0/ ?

**Comment by lwillacy** [comment]
For a CC with Attribution, I'd suggest:
https://creativecommons.org/licenses/by-nc-sa/4.0/

We get Attribution
NonCommercial uses
ShareAlike to ensure derivatives have same CC license

**Comment by fluffypony** [comment]
Non-commercial would preclude a media site from showing it with ads, no? The copyright holder (TLU) would them have to give them a limited license to do so?

**Comment by lwillacy** [comment]
NonCommercial is defined as “not primarily intended for or directed towards commercial advantage or monetary compensation.”  It is an area of gray but a media site showing with ads would very likely be a commercial use.  Accordingly, TLU would have to grant a license for such use.

If we use a commercial use license (i.e. https://creativecommons.org/licenses/by-sa/4.0/), anyone can use for any reason as long as TLU gets attribution and it's redistributed using same license.

My sense is we aren't concerned about the possibility a party may take the work for commercial use as long as it's still under a CC license so the commercial use license is likely ok.
