### ISSUE TITLE
incorrect notation explaining pedersen commitments

### ISSUE THREAD

**Issue by amiller** [tari-labs/tari-university#268]
The description of pedersen commitments below uses some wrong notation. It describes the process for generating a Schnorr subgroup of `Zp*` where  `p=2q+1` is a safe prime and the desired group is of prime order `q`. The process, specifically the 2nd step, involves selecting a random element `h` from `Zp*` and checking if it lies in the desired subgroup of order `q`. The problem is that this notation suggests the desired subgroup is `Zq*`, but this isn't the case at all. `Zq*` is a group of order `q-1` which isn't what's desired. Basically this should be fixed by removing any reference to `Zq*` in this section. An alternative could be to say that `h` is an element of `Gq`, a cyclic group of order `q`. Another alternative could be to say that `h` is isomorphic to an element of `Zq`, that is the additive group of `Zq` under addition that does have `q` elements.   
https://tlu.tarilabs.com/cryptography/bulletproofs-protocols/MainReport.html#pedersen-commitments-and-elliptic-curve-pedersen-commitments
![image](https://user-images.githubusercontent.com/71644/118300672-d28e2080-b4a7-11eb-8a60-edc4e2c4112e.png)

**Comment by delta1** [comment]
Thanks @amiller ! Any chance you would be willing to submit a PR to correct this please?
