### ISSUE TITLE
Typography concerns

### ISSUE THREAD

**Issue by jorpic** [tari-labs/tari-university#29]
On the last slide in Crypto101 `_k_a_` is rendered as `_ka` but it should be `kₐ`.

Actually for consistency it is better to use inline equation style for math variables everywhere.
Currently they are sometimes decorated with italics, e.g. on the last slide:

![image](https://user-images.githubusercontent.com/255417/43286725-9f13a97a-912b-11e8-818d-3d84bc965891.png)

Also, using period for multiplication (as in `s.G`) is a bit unusual. Why not to replace it with dot operator like `s⋅G`?

**Comment by hansieodendaal** [comment]
Thanks @jorpic , merged
