### ISSUE TITLE
Review: scriptless-scripts/introduction-to-scriptless-scripts.md

### ISSUE THREAD

**Issue by hansieodendaal** [tari-labs/tari-university#48]
@Kevoulee, thank you for adding the report to the repository, appreciated. I think the quality of the report will be enhanced if you could address these comments below:

- [x] Please try to use commas, colons and semicolons instead of dashes in sentences as far as possible, especially if there is only one dash. Dashes are confusing, especially if joined to other words. As an example, '_signatures-created_', '_MimbleWimble-which_' and '_validated-preventing_' suggest a join of some sort which it is not. Apply throughout. For reference see Wikipedia [comma](https://en.wikipedia.org/wiki/Comma) and [dash](https://en.wikipedia.org/wiki/Dash).

- [x] This is confusing '_Scriptless Scripts are digital signatures_'. In [2017-03 Bitcoin Expo Scriptless Scripts slides](https://download.wpsoftware.net/bitcoin/wizardry/mw-slides/2017-03-mit-bitcoin-expo/slides.pdf) Andrew Poelstra states: "Scriptless scripts:  magicking digital signatures so that they can only be created by faithful execution of a smart contract"

- [x] Please expand the references into the usual "[1] bla bla, bla bla, bla." style

- [x] Please correlate your information to that provided in [Layer 2 Scaling (part 2)](https://github.com/tari-labs/tari-university/blob/master/layer2scaling/more-landscape/landscape-update.md) w.r.t. Scriptless Scripts

- [x] Please provide a list of currently known scriptless scripts before section '**_The Role of Schnorr Signatures_**'

- [x] Suggest moving section '**_Adaptive Signatures_**' before section '**_Simultaneous Script less Scripts_**'

- [x] Let us use "block chain" everywhere instead of "blockchain" as per previous discussion.

- [x] Suggest renaming '**_MimbleWimble's Scriptless Script_**' to '**_MimbleWimble's Core Scriptless Script_**' 

- [x] It is not clear that s is the Schnorr signature when it is introduced.

- [x] The preferred use is '_Mimblewimble_' instead of '_MimbleWimble_'

- [x] Suggest using 'k: secret nonce' and 'x: private key' and adding it to the math block, in the presentation and the report

- [x] Edit: '_which was previously though to be unable_' to '_which was previously though**t** to be unable_'

- [x] Edit: '_valid if it offset by a secret value_' to '_valid if it **is** offset by a secret value_'

- [x] Edit: '_(s, R) is not valid but (s+t1,R ) is valid_' should be added to the end of the previous paragraph after '_occurrence_'

- [x] Please apply italic formatting to all mathematical symbols used 

- [x] With '_**Adaptive Signatures**_', P1 and t1 are introduced without definition.

- [x] With '_**Adaptive Signatures**_', for the non-informed, explain what is meant by (T1 , T1  + R1, s1 ) or (s+t1,R ). For example, the Mimblewimble white paper talks about terms like 'keypair (sk,pk)', 'Sign(sk,h)' and 'Verify(pk,h,s)'

- [x] With '_**Adaptive Signatures**_', something is missing here 'sent in addition to R (R+T).'

- [x] With '_**Adaptive Signatures**_', what is the meaning of subscript 1? The first party? Please define.

- [x] With '_**Atomic (Cross-chain Swaps) Example with Adaptive Signatures**_', what is the difference between t1 and t, T1 and T? Is T=tG?

- [x] With '_**MimbleWimble's Scriptless Script**_' the word **key** is equated with **confidential transition commitment** and **multisignature key of the owners** (_what is the difference?_), then we also have private and public keys. This is all a bit confusing. Maybe key should be qualified here every time it is used.

Thanks!

**Comment by CjS77** [comment]
On 4/12:
> ECDSA signatures (used in Bitcoin) have the same shape, but s lacks some structure and e commits to only the message

I don't think this is true. AFAIK ECDSA doesn't work because Schnorr signatures are linear (s = k + ex), whereas ECDSA sigs are not ( s = (e + x.Rx)/k ), so you cannot simply add signatures together..

s1 + s2 (Schnorr) = k1 + ex1 + k2 + ex2 = (k1+k2) + e(x1 + x2) <-- Still a signature
s1 + s2 (ECDSA) = e/k1 + e/k2 + x1 * Rx1/k1 + x2 * Rx2/k2 <-- can't simplify

**Comment by Kevoulee** [comment]
@hansieodendaal corrections completed

**Comment by hansieodendaal** [comment]
Hi @Kevoulee ,

I appreciate you doing these updates! Please see further comments below:

- [ ] Under '**_References_**' replace the numbered list with square brackets, i.e. "1. Crypto Innovation" becomes "[1] Crypto Innovation"

- [ ] Suggest  removing "See  Layer 2 Scaling Survey (part 2)" from the Table of Contents page and replacing it with "A brief introduction is also given in #5 Scriptless scripts, Layer 2 Scaling Survey (part 2)" at the bottom of '_**Definition of Scriptless Scripts**_'. Also link to the report here rather than the presentation.

With '_**The Role of Schnorr Signatures**_'

- [ ] Add "_P = xG_" below "_e=H(P||r||message)_"

With '_**Adaptive Signatures**_' some things are not logical and/or not made known to the reader. Although these comments seem cryptic, if applied the picture should become clear:

- [ ] Rather than"adapter" use "adaptor", even though both are grammatically correct. Also in the text change "adaptive signature" to "adaptor signature" 

- [ ] Combine "_T=tG_" and "_R=rG_" in one math block

- [ ] Delete "(this is all with respect to the first participant of the 2 of 2 case swap) where "

- [ ] Combine as follows: "where _t_ is the shared secret, _G_ the generator of discreet log hard group and _r_ the random nonce"

- [ ] Add below this par."... hard group and _r_ the random nonce":
"Using this information the second party generates _H(P||R+T||message)x_ where the coins to be swapped are contained within _message_"
"The first party can now calculate the complete signature _s_ such that'

- [ ] "The first participant, publishes to the second participant and other the following" to "The first participant then calculates and publishes the adaptor signature _s'_ to the second participant (and any one else listening)"

- [ ] Delete  "where s' is the adaptive signature"

- [ ] Change "The second participant can verify the adapter signature s'" to "The second participant can verify the adaptor signature s' by asserting s'G"

- [ ] "s'G? + R + H(P||R+T||message)P" should be "s'G =? R + H(P||R+T||message)P"

- [ ] Change "... cannot retrieve a valid signature and requires ECDLP solving to recover s'+t" to  "... cannot retrieve a valid signature from this and requires ECDLP solving to recover s'+t, which is virtually impossible"

- [ ] Change
"After validation of adaptive signature by the second participant, it is known:
Receipt of t ==> receipt of valid signature" 
to
"After the first participant broadcasts _s_ to claim the coins within _message_ the second participant can calculate the secret  _t_ from"
"_t = s - s'_"

With '**_Atomic (Cross-chain Swaps) Example with Adaptive Signatures_**'

- [ ] Ensure all mathematical symbols t and T are italic.

With '**_Mimblewimble's Core Scriptless Script_**'

- [ ] "confidential transition commitment" should be "confidential transaction commitment"

Thanks!

**Comment by hansieodendaal** [comment]
Thanks @Kevoulee , appreciated!
