### ISSUE TITLE
Private Digital Assets?

### ISSUE THREAD

**Issue by xeagu** [tari-labs/tari-university#5]
So Tari will operate as a merge mined sidechain with Monero that provides the ability to create digital assets. Ignoring the technical question of how this is done, is the intent to create private digital assets? On counterparty, assets are public - will Tari be built in a similar way or is the goal to design a system where ownership and transfer of digital assets is anonymous?

**Comment by CjS77** [comment]
The intent is to allow asset creators to define the rules for the assets they create. The plan for Tari is to implement a _privacy slider_ of sorts that will range from totally public to totally private with various options in between.
