### ISSUE TITLE
Review: tari-university/cryptography/fraud-proofs-1/MainReport.md

### ISSUE THREAD

**Issue by ksloven** [tari-labs/tari-university#65]
@Kevoulee @CjS77 @hansieodendaal here is the draft report for fraud proofs. Could you please review. Thanks

**Comment by hansieodendaal** [comment]
Hi @ksloven , thank you for submitting this report, I appreciate your contribution. We have not yet sorted out the review process, as a quality review requires a lead reviewer that is as responsible for the content as the author.

**Comment by hansieodendaal** [comment]
Hi @ksloven , I am only submitting general formatting/look & feel comments here. If you can incorporate these comments, I think the general quality of your report would be enhanced. I present these in the form of a task list, which is very handy to tick off once done. It will also show us which comments could not be implemented.

- [ ] References: Leave one space before every reference throughout, i.e. '_BTC outputs[17]_' should be '_BTC outputs [17]_'.

- [ ] References: Use spaces after each entry, i.e.: [1]<space>Title,<space>Author (if paper),<space>URL,<space>Date accessed.

- [ ] References: Use internal links for references and enable opening of URLs at the same time. This dead reference (**[1]**) in the text will become this 'live' reference (**[[1]][\[1\]]**) that is clickable and with data tool tip shown. See example below.

[\[1\]]: https://www.statista.com/statistics/647523/worldwide-bitcoin-blockchain-size 
"Size of the Bitcoin blockchain from 2010 to 2018, 
by quarter (in megabytes)"

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Referenced in the text like this:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`[[1]][\[1\]]`

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Include reference like this:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`[[1]][\[1\]]<space>Title,<space>Author (if paper),<space>URL,<space>Date accessed.`

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`[\[1\]]:<space>URL<space>`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`"Title line 1`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`Title line n"`

- [ ] Internal links: Use internal links without the GitHub URL included, for example `[introduction to fraud proofs](https://github.com/tari-labs/tari-university/blob/fraudproofs/cryptography/fraud-proofs-1/MainReport.md#what-are-fraud-proofs)` should become `[introduction to fraud proofs](#what-are-fraud-proofs)`

- [ ] Heading formatting: Apply consistent case formatting for headings. Some headings are sentence case, some title case and some lower case. This should be consistent for the different outline levels, example all level 3 headings may employ sentence case.

- [ ] Table of Contents: Insert a 'Contents' sections after 'Background' with a table of contents, reflecting the outline and internal links to the different headings. Example:

   `## Contents`
  `- [Fraud Proofs - easier said than done?](#Fraud-Proofs---easier-said-than-done?)`
&nbsp;&nbsp;  `- [Background](#Background)`
&nbsp;&nbsp;  `- [Contents](#Contents)`
&nbsp;&nbsp;  `etc.`

Thanks!

**Comment by hansieodendaal** [comment]
Hi @ksloven , can you please create a PR for your contribution? I will then just transfer all my comments as a review input (in check list form) onto the PR then we can close this issue. Thanks

**Comment by hansieodendaal** [comment]
This issue closed in favor of a PR, See Fraudproofs for PR #68
