### ISSUE TITLE
Review: tari-university/protocols/grin-beam-comparison: Grin vs BEAM, a comparison draft report review

### ISSUE THREAD

**Issue by philipr-za** [tari-labs/tari-university#67]
My first draft of the Grin vs BEAM report is pushed to the `grin-beam` branch. It will almost certainly need another proof read.

It was difficult to decide on what dimensions to perform this comparison. In the end they are both implementing Mimblewimble but they had a couple unique features that I discussed, they used different PoW algorithms but the biggest differences were in their Governance models and monetary policies.

I might have gone into too much depth on the Cuckoo cycle PoW but lets see what you think about the current layout. Let me know where you think I went into too much depth and where I summarized too much.

**Comment by philipr-za** [comment]
I reopened my PR as requested.

**Comment by hansieodendaal** [comment]
Thank you @philipr-za !
@SWvheerden please close this issue when you have transferred your comments.

**Comment by azaidelson** [comment]
Hi @philipr-za! 

I am Alexander, CEO of Beam. We have made some comments to your excellent work to reflect some misunderstandings and give some updates.

We made it in Google docs, so you can see the comments and suggestions.

The file is here: https://docs.google.com/document/d/1Ar-kqLfguj6QFkky_JW-StqgY_w2WBPEbpyXDnipVP0/edit

Would be awesome if you could review and update

**Comment by philipr-za** [comment]
Thats for the contribution, I will incorporate the new info into the article.

**Comment by azaidelson** [comment]
Thanks Philip! Looking forward to seeing it published!
