### ISSUE TITLE
mdBook needs an Introduction section

### ISSUE THREAD

**Issue by CjS77** [tari-labs/tari-university#86]
The `README.md` file should more-or-less be migrated over into mdBook.

But because it's mdBook, it can be a richer introduction. Instead of just listing the content (the TOC does this just fine), we can start to think about "Learning Paths", e.g.

Beginner's learning path (A set of introductory talks / presentations):
1. ...
2. ...

Presentations Only:
1. ...
2. ...

..and so on.

**Comment by hansieodendaal** [comment]
See Readme mdbook link #88
